name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-5.2.x"
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-5.2.x.sprockets-4.x"
          - ruby: 2.7
            gemfile: Gemfile

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec spec
        continue-on-error: ${{ matrix.gemfile == 'Gemfile' }}
      - name: Run rubocop
        run: bundle exec rubocop
